name: Lint
on: [pull_request]
jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install npm@7
        run: sudo npm i -g npm@7
      - name: Install dependencies
        run: npm ci
      - name: Run eslint
        run: npm run lint:es

  stylelint:
    name: stylelint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install npm@7
        run: sudo npm i -g npm@7
      - name: Install dependencies
        run: npm ci
      - name: Run stylelint
        run: npm run lint:style
