name: Lint
on: [pull_request]
jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run eslint
        run: |
          npm ci
          npm run lint:es

  stylelint:
    name: stylelint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run stylelint
        run: |
          npm ci
          npm run lint:style
